name = "BOCPD"
uuid = "71c670bf-f9ea-4f98-8ec4-4032b7591a87"
authors = ["Carl Bittendorf <carl.bittendorf@gmail.com> and contributors"]
version = "0.0.1"

[compat]
julia = "1.10.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
